version: '2.2'
services:
  redis01:
    image: redis
    container_name: redis01
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 320000M
        reservations:
          memory: 160000M
